# Generated by Django 3.0.7 on 2020-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentmessage',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentmessage',
            name='time_to_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoingmessage',
            name='caption',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
