# Generated by Django 3.0.7 on 2020-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_contentmessage_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'photo'), (3, 'video'), (4, 'url'), (5, 'document')]),
        ),
    ]
