# Generated by Django 3.0.7 on 2020-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_auto_20200628_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'text'), (2, 'photo'), (3, 'video'), (4, 'url'), (5, 'document'), (6, 'audio'), (7, 'media_group')]),
        ),
    ]
