# Generated by Django 3.0.7 on 2020-06-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_auto_20200629_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingmessage',
            name='file_id',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
