# Generated by Django 3.0.7 on 2020-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200704_1028'),
        ('sender', '0007_outgoingmessage_file_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmessage',
            options={'verbose_name': '"Рассылка контента"', 'verbose_name_plural': '"Рассылка контента"'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmessage',
            options={'verbose_name': '"Сообщение"', 'verbose_name_plural': '"Сообщения"'},
        ),
        migrations.AlterField(
            model_name='contentmessage',
            name='client',
            field=models.ManyToManyField(to='main.Client', verbose_name='Пользователь'),
        ),
    ]
