# Generated by Django 3.0.7 on 2020-07-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_auto_20200704_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmessage',
            options={'verbose_name': 'content message', 'verbose_name_plural': 'content messages'},
        ),
        migrations.AlterModelOptions(
            name='feedbackmessage',
            options={'verbose_name': 'feedback message', 'verbose_name_plural': 'feedback messages'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmessage',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
