# Generated by Django 3.0.7 on 2020-07-09 20:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200704_1813'),
        ('sender', '0010_feedbackmessage_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='send_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='time_to_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='client',
            field=models.ManyToManyField(to='main.Client', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='ButtonMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'text'), (2, 'photo'), (3, 'video'), (4, 'url'), (5, 'document'), (6, 'audio'), (7, 'media_group')])),
                ('caption', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField()),
                ('file_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('columns', models.SmallIntegerField()),
                ('buttons', django.contrib.postgres.fields.jsonb.JSONField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.ContentMessage')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
    ]
