# Generated by Django 3.0.7 on 2020-07-09 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_auto_20200709_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmessage',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.FeedBackMessage'),
        ),
    ]
