# Generated by Django 3.0.7 on 2020-07-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0012_auto_20200709_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmessage',
            name='buttons',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
