# Generated by Django 3.0.7 on 2020-07-26 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_client_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0014_auto_20200723_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('send_now', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('time_to_send', models.DateTimeField(blank=True, null=True)),
                ('client', models.ManyToManyField(to='main.Client', verbose_name='Пользователь')),
                ('group', models.ManyToManyField(to='main.ClientGroup')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'detailed answer',
                'verbose_name_plural': 'detailed answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'text'), (2, 'photo'), (3, 'video'), (4, 'url'), (5, 'document'), (6, 'audio'), (7, 'media_group')])),
                ('caption', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('file_id', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.DetailedAnswer')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'question',
            },
        ),
    ]
