# Generated by Django 3.0.7 on 2020-06-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_incomingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
