# Generated by Django 3.0.7 on 2020-07-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200704_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'telegram user', 'verbose_name_plural': 'telegram users'},
        ),
        migrations.AlterModelOptions(
            name='relationclientuser',
            options={},
        ),
    ]
