# Generated by Django 3.0.7 on 2020-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200704_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessageText',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('caption', models.CharField(max_length=128)),
            ],
        ),
    ]
