# Generated by Django 3.0.7 on 2020-07-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200704_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmessagetext',
            options={'verbose_name': 'system message text', 'verbose_name_plural': 'system message text'},
        ),
    ]
