# Generated by Django 3.0.7 on 2020-07-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_deletemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='man_or_woman',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'man'), (2, 'woman')], null=True),
        ),
    ]
