# Generated by Django 3.0.7 on 2020-07-19 12:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200716_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='after_chemistry',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='yoga',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
