# Generated by Django 3.0.7 on 2020-07-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200722_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='after_chemistry',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'да'), (0, 'нет')], null=True),
        ),
    ]
