# Generated by Django 3.0.7 on 2020-07-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_allowedchat_groupchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='chat_id',
            new_name='telegram_id',
        ),
    ]
