# Generated by Django 3.0.7 on 2020-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_client_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('group_message', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
            ],
        ),
    ]
