# Generated by Django 3.0.7 on 2020-07-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_clienttogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttogroup',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Client'),
            preserve_default=False,
        ),
    ]
