# Generated by Django 3.0.7 on 2020-07-27 20:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_clienttogroup_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hashtag',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
