# Generated by Django 3.0.7 on 2020-08-14 13:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200728_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hashtag',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
