# Generated by Django 3.0.7 on 2020-09-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200814_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='set',
            field=models.SmallIntegerField(choices=[(1, 'Первый поток'), (2, 'Второй поток'), (3, 'Третий поток'), (4, 'Четвертый поток'), (5, 'Пятый поток')], default=1),
        ),
    ]
