# Generated by Django 3.0.7 on 2020-07-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sender', '0013_auto_20200710_0012'),
        ('main', '0011_auto_20200704_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.ButtonMessage')),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.IntegerField()),
                ('state', models.SmallIntegerField(choices=[(1, 'ожидаем ответа'), (2, 'ответ получен')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.ButtonMessage')),
            ],
        ),
    ]
