# Generated by Django 3.0.7 on 2020-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message_id'], name='analytics_m_message_88d069_idx'),
        ),
    ]
