# Generated by Django 3.0.7 on 2020-07-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_client_avatar'),
        ('sender', '0015_detailedanswer_questionmessage'),
        ('analytics', '0002_auto_20200711_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.QuestionMessage')),
            ],
            options={
                'verbose_name': 'report with detailed',
                'verbose_name_plural': 'report with detailed',
            },
        ),
    ]
