# Generated by Django 3.0.7 on 2020-07-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_client_avatar'),
        ('sender', '0015_detailedanswer_questionmessage'),
        ('analytics', '0003_reportfordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.IntegerField()),
                ('state', models.SmallIntegerField(choices=[(1, 'ожидаем ответа'), (2, 'ответ получен')])),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.QuestionMessage')),
            ],
        ),
        migrations.AddIndex(
            model_name='questionstatus',
            index=models.Index(fields=['message_id'], name='analytics_q_message_c80fb1_idx'),
        ),
    ]
