# Generated by Django 3.0.7 on 2020-08-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200728_0034'),
        ('analytics', '0004_auto_20200726_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.SmallIntegerField(choices=[(1, 'У тебя уже закончился период радикального лечения (операция)?'), (2, 'Ты находишься на стадии химеотерапии или после химеотерапии?'), (3, 'Ты проходишь вспомогательное лечение?'), (4, 'Ты находишься на стадии выздоровления (ремиссии)?'), (5, 'Ты чувствуешь себя нормально, бодро и есть силы немного позаниматься?'), (6, 'Самочувствие нестабильное, сил мало?'), (7, 'Индекс массы тела меньше 20.5'), (8, 'Наблюдалась ли у тебя потеря веса на протяжении предыдущих 3-х месяцев?'), (9, 'Намерено ли было совершено изменение веса?'), (10, 'Было ли снижено питание на предыдущей неделе?'), (11, 'Было ли снижено потребление жидкости на предыдущей неделе?'), (12, 'Отмечаете ли Вы затрудненное глотание?'), (13, 'Пожалуйста, выберете число (от 0 до 10), которое наилучшим образом описывает то, как сильно вы переживали стресс за последнюю неделю, включая сегодняшний день.')])),
                ('answer', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client')),
            ],
        ),
    ]
