# Generated by Django 3.0.7 on 2020-08-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_anketa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anketa',
            options={'verbose_name': 'anketa', 'verbose_name_plural': 'anketa'},
        ),
    ]
