# Generated by Django 3.0.7 on 2020-10-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_groupname_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfordetail',
            name='answer',
            field=models.CharField(max_length=2048),
        ),
    ]
