command = '/srv/www/bot/venv/bin/gunicorn'
pythonpath = '/srv/www/bot'
bind = '0.0.0.0:8000'
workers = 2
limit_request_fields = 32000
limit_request_field_size = 0
raw_env = 'DJANGO_SETTINGS_MODULE=bot.settings'
reload = True
name = 'bot'