# Generated by Django 3.0.7 on 2020-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileloader',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
