# Generated by Django 3.0.7 on 2020-06-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_fileloader_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileloader',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
