# Generated by Django 3.0.7 on 2020-06-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200628_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileloader',
            name='telegram_id',
        ),
        migrations.AlterModelTable(
            name='fileloader',
            table='file',
        ),
    ]
