# Generated by Django 3.0.7 on 2020-07-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200629_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileloader',
            options={'verbose_name': 'Загрузка файлов', 'verbose_name_plural': 'Загрузка файлов'},
        ),
    ]
